### ISSUE TITLE
Generating Time Series from a Pre-Trained Model

### ISSUE THREAD

**Issue by MLaser42** [jsyoon0823/TimeGAN#17]
Dear @jsyoon0823, thanks for your awesome work!
I was wondering how to generate time-series from a pre-trained model.
Could you please give me some hints?
Best

Marco

**Comment by jsyoon0823** [comment]
To generate time-series from a pre-trained model, you first need to save the trained model.
In order to do that, you need to modify the original code somehow as follows.

Please see the following links as an example to save, restore, and run.
https://stackoverflow.com/questions/33759623/tensorflow-how-to-save-restore-a-model

Note that you need to follow the descriptions with TF < 2.
Thanks!
