### ISSUE TITLE
MinMaxScaler

### ISSUE THREAD

**Issue by Zepp3** [jsyoon0823/TimeGAN#27]
Hi!

Great work with the timeGAN! I got 2 questions concerning the normalization: why does the data get scaled in data_loader.py and then again in timegan.py? And why not use fro example a MinMaxScaler from sklearn with the advantage that it accepts strings?

Kind regards!

**Comment by jsyoon0823** [comment]
Thanks for your interest in our paper.
Please see my answers below.

(1) Normalization duplication
- We would like to make the timeGAN code itself as normalization
independent. Therefore, we include the normalization in timeGAN code.
- For data_loader, we can remove the normalization. We added there as well
due to some baseline comparison experiments. But without that, the
performance of timeGAN will be the same.

(2) sklearn
- Acknowledged that we can use the sklearn MinMax function.
- There is no reason that we do not use sklearn MinMax. We just use our own
MinMax because the function is simple.

Thanks!

**Comment by Zepp3** [comment]
Hi @jsyoon0823 ,
thank you for your answers, very helpful!
