### ISSUE TITLE
Random vector z_t from the Wiener process

### ISSUE THREAD

**Issue by TMmichi** [jsyoon0823/TimeGAN#33]
Firstly, many thanks for your countless efforts on the work of TimeGAN and the distribution of the package to the community. I'm really enjoying implementing it!

One question to ask regarding the random vector, from the theory within the paper and the code implementation.

In the paper, z_t is thought to be the Wiener process which I think is reasonable since the time correlation is present throughout the series.
In the code implementation, however, I've noticed that the way you generate the random vector is via the `random_generator` function from the `utils.py`, which samples its element from the NumPy uniform function. 

As far as I know, the NumPy uniform function is independent of the previously sampled value and does not form a Wiener process.

Am I missing something here?

Thanks.

**Comment by thj926** [comment]
> Firstly, many thanks for your countless efforts on the work of TimeGAN and the distribution of the package to the community. I'm really enjoying implementing it!
> 
> One question to ask regarding the random vector, from the theory within the paper and the code implementation.
> 
> In the paper, z_t is thought to be the Wiener process which I think is reasonable since the time correlation is present throughout the series.
> In the code implementation, however, I've noticed that the way you generate the random vector is via the `random_generator` function from the `utils.py`, which samples its element from the NumPy uniform function.
> 
> As far as I know, the NumPy uniform function is independent of the previously sampled value and does not form a Wiener process.
> 
> Am I missing something here?
> 
> Thanks.
Same question.

**Comment by thj926** [comment]
↑↑↑
Same question.

**Comment by jsyoon0823** [comment]
Thanks for the interest in our paper.

Yes. We first implement TimeGAN with Wiener process.
But after some times, we also noticed that the performances are similar without using Wiener process (just using iid random variables).
Therefore, to make the implementation simpler, we finalize to use iid random variables as the random inputs in time-series.

Hopefully, this can be answers to your questions.

Thanks!

**Comment by thj926** [comment]
Many thanks. 发自 网易邮箱大师 ---- Replied mail ---- From Jinsung ***@***.***> Date 10/03/2021 14:22 To ***@***.***> Cc ***@***.******@***.***> Subject Re: [jsyoon0823/TimeGAN] Random vector z_t from the Wiener process (#33) Thanks for the interest in our paper. Yes. We first implement TimeGAN with Wiener process. But after some times, we also noticed that the performances are similar without using Wiener process (just using iid random variables). Therefore, to make the implementation simpler, we finalize to use iid random variables as the random inputs in time-series. Hopefully, this can be answers to your questions. Thanks! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
