### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by Atrin78** [jsyoon0823/TimeGAN#7]
I use tutorial_timegan.ipynb with its default hyperparameters but I can't reproduce the results from the paper. I get a discriminative score around 0.133 for the stock dataset and 0.498 for the energy dataset. The predictive score for the energy dataset is around 0.32 which is also higher than the score reported in the paper.

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.
Unfortunately, the notebook codebases use simple "default" hyper-parameter that the users can easily achieve the results within a short execution time. (Because this is a "tutorial" codebase)
With proper hyper-parameters will improve the performance and you can reproduce the results reported in the paper. (At least you can get much better performance with main_timegan.py)
You can also use hyper-parameter optimization using discriminative and predictive scores as well.
Thanks!
