### ISSUE TITLE
On "Mix the datasets (to make it similar to i.i.d)"

### ISSUE THREAD

**Issue by carloallocca** [jsyoon0823/TimeGAN#78]
Dear @jsyoon0823,

When you are laoding the data with "def real_data_loading(data_name, seq_len):"  you mix the dataset mentioning "# Mix the datasets (to make it similar to i.i.d)". I wonder why you decided to do so? 

Wouldn't this way lead to change of characteristics of the time-serie for which the TimeGAN is evaluated? 

Thank you in advance for your reply and shring your research and project. 

Best Regards,
Carlo

**Comment by jsyoon0823** [comment]
Time-GAN's objective is to generate synthetic and iid time-series samples.
In order to do that, we first need to make one time-series into multiple iid time-series samples.
More specifically, we use one very long time-series data as the input.
Then, we divide them into multiple chunks. Still those chunks are correlated because those are coming from the same one time-series.
To remove the correlation, we mix them randomly.

Note that the objective of timeGAN is not generating one time-series data.
